'use strict'
const assert = require('assert')
const fs = require('fs')
const path = require('path')
const { parseCircuitTable, parseStatusTable, buildStatusMap, buildStatusOutputMap } = require('../')
const buf = fs.readFileSync(path.join(__dirname, 'fixtures', 'SugarShack-20260927-01.zcf'))
const status = parseStatusTable(buf, parseCircuitTable(buf))
assert(status)
assert.strictEqual(status.format, 'status-table-bit-record')
assert.strictEqual(status.recordCount, 102)
const byName = buildStatusMap(status)
assert.deepStrictEqual([byName.get('100L Fridge').statusModule, byName.get('100L Fridge').statusBit, byName.get('100L Fridge').statusMask], [0x14, 13, 1 << 13])
assert.deepStrictEqual([byName.get('200L Fridge').statusModule, byName.get('200L Fridge').statusBit, byName.get('200L Fridge').statusMask], [0x1A, 13, 1 << 13])
assert.deepStrictEqual([byName.get('200L Fridge Light').statusModule, byName.get('200L Fridge Light').statusBit, byName.get('200L Fridge Light').statusMask], [0x1A, 1, 1 << 1])
const byOutput = buildStatusOutputMap(status)
assert.strictEqual(byOutput.get('20:13').name, '100L Fridge')
assert.strictEqual(byOutput.get('26:1').name, '200L Fridge Light')
console.log('CZone status-table parser tests passed')
